apiVersion: v1
kind: Pod
metadata:
  name: kubeturbo
  labels:
    name: kubeturbo
spec:
  nodeSelector:
    kubeturbo: deployable
  containers:
  - name: kubeturbo
    # The image is the same one as used in non-OpenShift k8s distributions
    image: vmturbo/kubeturbo:60
    args:
      # Need to specify the admin.kubeconfig file for OS version before 3.6
      # - --kubeconfig=/etc/kubeturbo/admin.kubeconfig
      - --turboconfig=/etc/kubeturbo/config
      - --k8sVersion=1.6
      - --kubelet-https=true
      - --kubelet-port=10250
    volumeMounts:
    - name: vmt-config
      mountPath: /etc/kubeturbo
      readOnly: true
  volumes:
  - name: vmt-config
    hostPath:
      path: /etc/kubeturbo
  restartPolicy: Always
